# -*- coding: utf-8 -*-
"""Cálculo_viagem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16an_FBXDm3KK2RYvWNuz8pOhC4yCbqdI
"""

dias = int(input('Quantas diárias? '))
cidade = input('Qual cidade? [Salvador, Fortaleza, Natal ou Aracaju] ')


passeio = [200, 400, 250, 300]
kms = [850, 800, 300, 550]

km_l = 14
preco_gasolina = 5
diaria_hotel =  150


def gasto_hotel():
  diaria = diaria_hotel * dias
  return(diaria)

diaria = gasto_hotel()

def gasto_gasolina(cidade):

  if cidade  == 'Salvador':
    return(2 * kms[0] * preco_gasolina) / km_l
  elif cidade == 'Fortaleza':
    return(2 * kms[1] * preco_gasolina) / km_l
  elif cidade == 'Natal':
    return(2 * kms[2] * preco_gasolina) / km_l
  elif cidade == 'Aracaju':
    return(2 * kms[3] * preco_gasolina) / km_l

def gasto_passeio(cidade, dias):

  if cidade == 'Salvador':
    return(passeio[0] * dias)
  elif cidade == 'Fortaleza':
    return(passeio[1] * dias)
  elif cidade == 'Natal':
    return(passeio[2] * dias)
  elif cidade == 'Aracaju':
    return(passeio[3] * dias)


gastos = gasto_hotel() + gasto_gasolina(cidade) + gasto_passeio(cidade, dias)

print(f"Com base nos gastos definidos, uma viagem de {dias} dias para {cidade} saindo de Recife custaria {round(gastos, 2)} reais")